# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {
# META     "lakehouse": {
# META       "default_lakehouse": "5172f713-ade0-41bf-8eab-aaa0eb32b9a7",
# META       "default_lakehouse_name": "OJ_Sales_LH",
# META       "default_lakehouse_workspace_id": "ff07ab2f-c4d6-4e29-98d0-ceb497314e74",
# META       "known_lakehouses": [
# META         {
# META           "id": "5172f713-ade0-41bf-8eab-aaa0eb32b9a7"
# META         }
# META       ]
# META     }
# META   }
# META }

# MARKDOWN ********************

# ## Download OJ_Sales Dataset and save it to Lakehouse Files/

# CELL ********************

# Azure storage access info for open dataset diabetes
blob_account_name = "azureopendatastorage"
blob_container_name = "ojsales-simulatedcontainer"
blob_relative_path = "oj_sales_data"
blob_sas_token = r"" # Blank since container is Anonymous access
    
# Set Spark config to access  blob storage
wasbs_path = f"wasbs://%s@%s.blob.core.windows.net/%s" % (blob_container_name, blob_account_name, blob_relative_path)
spark.conf.set("fs.azure.sas.%s.%s.blob.core.windows.net" % (blob_container_name, blob_account_name), blob_sas_token)
print("Remote blob path: " + wasbs_path)
    
# Spark reads csv
df = spark.read.csv(wasbs_path, header=True)
# ATTENTION: AI-generated code can include errors or operations you didn't intend. Review the code in this cell carefully before running it.

#  Save as a file in Lakehouse Files/
df.write.mode("overwrite").parquet("Files/oj_sales")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

display(df.limit(5))

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

import pandas as pd

df = df.toPandas()


# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

df.info()

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

df.shape

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

df = df.sample(n=500, random_state=1)
    
df['WeekStarting'] = pd.to_datetime(df['WeekStarting'])
df['Quantity'] = df['Quantity'].astype('int')
df['Advert'] = df['Advert'].astype('int')
df['Price'] = df['Price'].astype('float')
df['Revenue'] = df['Revenue'].astype('float')
    
df = df.reset_index(drop=True)
df.head(4)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Code generated by Data Wrangler for pandas DataFrame

def clean_data(df):
    # Replace all instances of "." with " " in column: 'Brand'
    df['Brand'] = df['Brand'].str.replace(".", " ", case=False, regex=False)
    # Capitalize the first character in column: 'Brand'
    df['Brand'] = df['Brand'].str.title()
    return df

df_clean = clean_data(df.copy())
display(df_clean)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

df = df_clean

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

df['Brand'].unique()

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# ## Apply one-hot encoding on Brand column

# CELL ********************


# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Code generated by Data Wrangler for pandas DataFrame

import pandas as pd

def clean_data(df):
    # One-hot encode column: 'Brand'
    insert_loc = df.columns.get_loc('Brand')
    df = pd.concat([df.iloc[:,:insert_loc], pd.get_dummies(df.loc[:, ['Brand']]), df.iloc[:,insert_loc+1:]], axis=1)
    return df

df_clean = clean_data(df.copy())
display(df_clean)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Code generated by Data Wrangler for pandas DataFrame

def clean_data(df):
    # Filter rows based on column: 'Store'
    df = df[df['Store'] == "1227"]
    # Sort by column: 'Price' (descending)
    df = df.sort_values(['Price'], ascending=[False], key=lambda s: s.apply(str) if s.name in ['Price'] else s)
    return df

df_clean_2 = clean_data(df.copy())
display(df_clean_2)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Code generated by Data Wrangler for pandas DataFrame

def clean_data(df):
    # Change column type to datetime64[ns] for column: 'WeekStarting'
    df = df.astype({'WeekStarting': 'datetime64[ns]'})
    # Change column type to float64 for column: 'Price'
    df = df.astype({'Price': 'float64'})
    # Change column type to int64 for column: 'Store'
    df = df.astype({'Store': 'int64'})
    # Change column type to float64 for column: 'Revenue'
    df = df.astype({'Revenue': 'float64'})
    # Change column type to int64 for column: 'Quantity'
    df = df.astype({'Quantity': 'int64'})
    # Change column type to int64 for column: 'Advert'
    df = df.astype({'Advert': 'int64'})

df_clean_3 = clean_data(df.copy())
display(df_clean_3)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }
